---
title: "MN COVID-19 Cases"
author: "Kyle E. Chambers (kchamber@gustavus.edu)"
date: "3/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(janitor)
library(here)
library(tibbletime)
library(scales)

theme_set(theme_minimal())
```

```{r}
rolling_mean_7 <- rollify(mean, window = 7)
```


```{r}
all_confirmed <- 
  read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv") %>%
  clean_names() %>% 
  filter(province_state %in% c("Minnesota", "Virginia", "Oklahoma")) %>% 
  add_column("measure" = "confirmed")

all_recovered <- 
  read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Recovered.csv") %>%
  clean_names() %>% 
  filter(province_state %in% c("Minnesota", "Virginia", "Oklahoma")) %>% 
  add_column("measure" = "recovered")

all_deaths <- 
  read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Deaths.csv") %>%
  clean_names() %>% 
  filter(province_state %in% c("Minnesota", "Virginia", "Oklahoma")) %>% 
  add_column("measure" = "deaths")

all_cases <- 
  bind_rows(all_confirmed, all_deaths, all_recovered) %>% 
  select(measure, "state" = province_state, everything(), -country_region, -lat, -long)

all_cases_long <-
  all_cases %>% 
  pivot_longer(names_to = "date", values_to = "cases", c(-measure, -state)) %>% 
  mutate(date = str_remove(date, "x")) %>% 
  mutate(date = mdy(date)) %>% 
  group_by(measure) %>% 
  mutate(new_cases = cases - lag(cases, 1)) %>%
  mutate(moving_avg = rolling_mean_7(new_cases)) %>% 
  ungroup() %>% 
  filter(date >= "2020-03-01")

just_confirmed <- 
  all_cases_long %>% 
  filter(measure == "confirmed")

confirmed_totals <- 
  all_cases_long %>% 
  group_by(state) %>% 
  summarize(total_cases = sum(new_cases)) %>% 
  mutate(total_cases = paste0(total_cases, " TOTAL CASES", sep = " "))

```


```{r}

p <- 
ggplot(just_confirmed, aes(x = date, y = new_cases)) +
  geom_col(alpha = 0.2, fill = "tomato") +
  geom_area(aes(y = moving_avg), fill = "tomato", alpha = 0.5) +
  geom_line(aes(y = moving_avg), color = "red") +
  facet_wrap(.~state) +
  theme(
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.minor.y = element_blank(),
    strip.text = element_text(size = 14, face = "bold", hjust = 0),
    plot.title = element_text(size = 18, face = "bold"),
    axis.ticks.x = element_line(color = "black"),
    axis.line.x = element_line(color = "black")
  ) +
  labs(title = "The number of new cases each day",
      subtitle = "7-day average shown in red",
      y = NULL,
      x = NULL)

p +  geom_text(data = confirmed_totals, aes(x = as.Date("2020-03-01", "%Y-%m-%d"), y = Inf, label = total_cases), hjust = 0, vjust = 1, color = "gray62")

```

